### ISSUE TITLE
Add URIs for external resources / ontologies

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf-common-schema#45]
Currently, with the new `ExternalResources` data type, each term is associated with an external resource (e.g., ontology), a unique identifier at the resource, and the URI for the resource entity.

Users would also like to associate a URI for the external resource. For example, the external resource "NCBITaxon" would have the URI "https://www.ncbi.nlm.nih.gov/taxonomy" associated with it. To normalize these data in the "resources" table, we should add a new table with fields (name, uri) and change the "resource_name" field in the "resources" table to be an index (foreign key) into the new table. 

This change requires further feedback and coordination with ontology users.

**Comment by rly** [comment]
@ajtritt @oruebel Should we include this change and release hdmf-common-schema 1.3.0 or hold this off until a later release?

**Comment by ajtritt** [comment]
We'll need to include it. The hdmf code will need these types defined in the schema, otherwise `TypeMap.register_class` will choke.

**Comment by rly** [comment]
To be clear, I mean, should we include the addition of an additional URI for the resource, on top of everything that has already been implemented in HDMF and set in hdmf-common-schema. AFAIK, the proposed change has not yet been implemented in either the schema or HDMF.

**Comment by ajtritt** [comment]
> To be clear, I mean, should we include the addition of an additional URI for the resource,

oops... didn't read the issue in detail. This might take some time to add. If we need to make a release, then I suggest not letting this hold it up

**Comment by oruebel** [comment]
Since this is still in development, I don't think it will be an issue to add this later in another release.

**Comment by rly** [comment]
Great, thanks for the input.

**Comment by oruebel** [comment]
1. Change the name of the``ResourceTable`` to ``EntityTable``
2. Add ``ResourceTable`` with columns ``id``, ``name``, and ``uri`` to describe the resources
3. Change ``recource_name`` column in the ``ResourceTable`` to ``resource_id`` to point to the new ``ResourceTable``
4. Update tests for ``EntityTable`` and add tests for ``ResourceTable``
5. Write documentation describing the structure for managing ``ExternalResources``
6. Write documentation describing the use of  ``ExternalResources``

**Comment by rly** [comment]
The schema parts of this issue have been resolved by #49.

**Comment by oruebel** [comment]
@rly @mavaylon1 has this issue been completed?

**Comment by rly** [comment]
This is done.
