### ISSUE TITLE
hdmf schema language

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf-common-schema#6]
I think there is a bit of unclarity here with regards to the schema language. I do not see any documentation about the HDMF schema language. We do have the [schema-language readthedocs](https://schema-language.readthedocs.io/en/latest/index.html), but that page states that it is for NWB and contains the NWB-specific keys `neurodata_type_def` and `neurodata_type_inc`. If we want to have a more general schema language we would need 

1) A page describing the HDMF schema language. It may be preferable to just modify the existing NWB specification language.
2) A formal specification for changing the names of keys. I suppose this should be added to the schema language as well.
3) A json schema validator for the HDMF schema language.

**Comment by oruebel** [comment]
I think all 3 items sound reasonable. 

>     2\. A formal specification for changing the

I think this would probably be part of the namespace specification or we'd need to add a header for the files. 

>     3\. A json schema validator ...

An alternative would be to add ``validate`` functions on the schema specification  classes in HDMF.

**Comment by rly** [comment]
I believe points 1 and 3 are resolved with the creation of https://github.com/hdmf-dev/hdmf-schema-language
I also just added a section in the readme there to address point 2.
